### ISSUE TITLE
SBP: Benchmarks

### ISSUE THREAD

**Issue by NachoPal** [CESSProject/cess#43]
Improve benchmarks for `file-bank` and replace the fixed weights

**Comment by swowk** [comment]
cc @ytqaljn

**Comment by ytqaljn** [comment]
Thank you for your suggestion. At present, we are making a big change to the code, so there is no way to write the corresponding benchmark for the time being, because even if it is written, it will not be suitable for calls that will be changed in the future. After the change, we will rewrite the benchmark. We expect to complete the preparation of benchmark in early July, when we will reply to you with PR link
